/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./components/Hello.vue')['default']
    InputDate: typeof import('./components/forms/InputDate.vue')['default']
    InputEmail: typeof import('./components/forms/InputEmail.vue')['default']
    InputName: typeof import('./components/forms/InputName.vue')['default']
    InputPassword: typeof import('./components/forms/InputPassword.vue')['default']
    Phaser: typeof import('./components/Phaser.vue')['default']
    PhaserGame: typeof import('./components/game/PhaserGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
