/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Example: typeof import('./components/Example.vue')['default']
    Hello: typeof import('./components/Hello.vue')['default']
    Phaser: typeof import('./components/Phaser.vue')['default']
    PhaserGame: typeof import('./components/game/PhaserGame.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
